import type { Metadata } from "next";
import "./globals.css";
import { montserrat, cormorant, mulish } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="fantasy" lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Prevent FART (Flash of Accidental/Unstyled Theme)
              if (localStorage.getItem("theme") === null) {
                document.documentElement.setAttribute("data-theme", "fantasy");
              } else {
                document.documentElement.setAttribute("data-theme", localStorage.getItem("theme"));
              }
            `,
          }}
        />
      </head>
      <body
        className={`${montserrat.variable} ${cormorant.variable} ${mulish.variable} antialiased`}
      >
          {children}
      </body>
    </html>
  );
}
