import type { EssayEntry } from './types';
import { assetUrl } from '@/lib/assets';

export const genesisSeedEssay: EssayEntry = {
  "title": "You Can Look Now",
  "slug": "you-can-look-now",
  "deck": "Meeting land, seed, and visible correspondence in Genesis 1:9-13.",
  "category": "religion",
  "status": "published",
  "publicationDate": "September 2026",
  "publicationDateIso": "2026-09-01",
  "readingTime": "10 minute read",
  "image": assetUrl('/images/whydive/you-can-look-now-hero.png'),
  "series": {
    "title": "Knowing God in Genesis",
    "slug": "knowing-god-in-genesis",
    "order": 5,
    "label": "Genesis 1:9-13",
    "role": "installment"
  },
  "scriptureRange": "Genesis 1:9-13",
  "topics": ["Genesis", "creation", "land", "seed", "correspondence", "evidence", "knowing God"],
  "tags": ["Genesis 1", "seed", "creation", "evidence", "Scripture", "interpretation", "religion"],
  "claimAuditSlug": "you-can-look-now",
  "sourceNote": "This essay is adapted from an internal Relational Knowledge of God draft on Genesis 1:9-13. It continues WhyDive's close reading of Genesis by attending to what the passage gives, what the reader can now observe, and how testimony and visible correspondence begin to work together.",
  "bibliography": [
    {
      "label": "Nachmanides on Genesis 1:11, English text via Sefaria.",
      "href": "https://www.sefaria.org/Ramban_on_Genesis.1.11"
    }
  ],
  "sections": [
    {
      "blocks": [
        { "type": "paragraph", "text": "There is something remarkable inside a piece of fruit." },
        { "type": "paragraph", "text": "A future." },
        { "type": "paragraph", "text": "Cut open an apple, a peach, a mango, or almost any fruit you know, and there it is: seed." },
        { "type": "paragraph", "text": "You do not need to understand genetics to recognize what it can do. You do not need to know the chemistry of germination. You do not need to know the Hebrew word for seed." },
        { "type": "paragraph", "text": "Plant one." },
        { "type": "paragraph", "text": "Wait." },
        { "type": "paragraph", "text": "Watch." },
        { "type": "paragraph", "text": "Genesis did not begin here." },
        { "type": "paragraph", "text": "It began somewhere we cannot go." },
        { "type": "quote", "text": "In the beginning God created the heaven and the earth.", "cite": "Genesis 1:1, KJV" },
        { "type": "paragraph", "text": "None of us saw that beginning." },
        { "type": "paragraph", "text": "We did not watch the first light appear. We did not stand beside those first waters. We were not there when God made the expanse. We still have questions about what some of the language describing those realities even means." },
        { "type": "paragraph", "text": "At first, almost everything has to be told to us." },
        { "type": "paragraph", "text": "But by the third day, something is changing." },
        { "type": "paragraph", "text": "The world God is describing is beginning to look like ours." },
        { "type": "paragraph", "text": "And that changes the reader's relationship to the story." }
      ]
    },
    {
      "title": "We Have Heard This Voice Before",
      "blocks": [
        { "type": "paragraph", "text": "And God said..." },
        { "type": "paragraph", "text": "By Genesis 1:9, those words are no longer new." },
        { "type": "paragraph", "text": "The first time God spoke, we had no narrated history with His speech." },
        { "type": "paragraph", "text": "Let there be light." },
        { "type": "paragraph", "text": "Then there was light." },
        { "type": "paragraph", "text": "He spoke again." },
        { "type": "paragraph", "text": "Reality again corresponded with what He had said." },
        { "type": "paragraph", "text": "So when we reach the third day and hear:" },
        { "type": "quote", "text": "And God said..." },
        { "type": "paragraph", "text": "we are not standing where we stood before." },
        { "type": "paragraph", "text": "We have been watching." },
        { "type": "paragraph", "text": "God tells us what is going to happen before the narrative gives us the result. Then we are allowed to compare the two." },
        { "type": "paragraph", "text": "That matters." },
        { "type": "paragraph", "text": "If someone tells you what they intended only after something happened, you have their explanation." },
        { "type": "paragraph", "text": "If they tell you beforehand, something else becomes possible." },
        { "type": "paragraph", "text": "You can compare." },
        { "type": "paragraph", "text": "Genesis has repeatedly placed its reader in exactly that position." },
        { "type": "paragraph", "text": "God speaks." },
        { "type": "paragraph", "text": "We hear." },
        { "type": "paragraph", "text": "Something happens." },
        { "type": "paragraph", "text": "We look." },
        { "type": "paragraph", "text": "And now He speaks again." }
      ]
    },
    {
      "title": "Let the Dry Land Appear",
      "blocks": [
        { "type": "paragraph", "text": "God says:" },
        { "type": "quote", "text": "Let the waters under the heaven be gathered together unto one place, and let the dry land appear.", "cite": "Genesis 1:9, KJV" },
        { "type": "paragraph", "text": "Appear is easy to read past." },
        { "type": "paragraph", "text": "So we tested it." },
        { "type": "paragraph", "text": "The picture survived outside English." },
        { "type": "paragraph", "text": "The Hebrew really does use seeing-and-appearing language. Ancient Greek and Latin preserve the idea of appearing or becoming visible. Some Spanish translations make the picture particularly vivid with language suggesting uncovering or exposing what had not been visible. Korean likewise preserves the sense of something coming into view." },
        { "type": "paragraph", "text": "Those languages do not prove some hidden theology inside the word." },
        { "type": "paragraph", "text": "They do something more useful." },
        { "type": "paragraph", "text": "They tell us that English did not invent the basic picture." },
        { "type": "paragraph", "text": "Something previously unavailable to sight becomes visible." },
        { "type": "paragraph", "text": "And perhaps that should make us notice something larger." },
        { "type": "paragraph", "text": "Genesis keeps letting the reader see." },
        { "type": "paragraph", "text": "God could simply act and allow the narrator to report what He did afterward." },
        { "type": "paragraph", "text": "Instead, we repeatedly hear what He says before we encounter the result." },
        { "type": "paragraph", "text": "Now something is going to appear." },
        { "type": "paragraph", "text": "And the reader has been positioned to watch." }
      ]
    },
    {
      "title": "God Gives Us Words",
      "blocks": [
        { "type": "paragraph", "text": "Then God does something He has done before." },
        { "type": "paragraph", "text": "He names." },
        { "type": "paragraph", "text": "The dry land He calls Earth." },
        { "type": "paragraph", "text": "The gathered waters He calls Seas." },
        { "type": "paragraph", "text": "Earlier He called the light Day, the darkness Night, and the expanse Heaven." },
        { "type": "paragraph", "text": "We should be careful about claiming why He names. Naming may do several things in this narrative." },
        { "type": "paragraph", "text": "But one effect is difficult to miss." },
        { "type": "paragraph", "text": "The land does not need the narrator to tell it that God calls it Earth." },
        { "type": "paragraph", "text": "The seas do not need to read Genesis to discover their name." },
        { "type": "paragraph", "text": "The reader receives that information." },
        { "type": "paragraph", "text": "Day." },
        { "type": "paragraph", "text": "Night." },
        { "type": "paragraph", "text": "Heaven." },
        { "type": "paragraph", "text": "Earth." },
        { "type": "paragraph", "text": "Seas." },
        { "type": "paragraph", "text": "The world is not only becoming more differentiated. It is becoming more describable." },
        { "type": "paragraph", "text": "And the narrative gives us God's own designations for what we are being shown." },
        { "type": "paragraph", "text": "Whatever else naming accomplishes, we have been given words with which to refer to this increasingly differentiated world." }
      ]
    },
    {
      "title": "Then Something New Happens",
      "blocks": [
        { "type": "paragraph", "text": "God speaks again." },
        { "type": "paragraph", "text": "But this time His words are different:" },
        { "type": "quote", "text": "Let the earth bring forth...", "cite": "Genesis 1:11, KJV" },
        { "type": "paragraph", "text": "That deserves attention." },
        { "type": "paragraph", "text": "God does not simply say, \"Let there be plants.\"" },
        { "type": "paragraph", "text": "Something already present in the created world now has a function in what happens next." },
        { "type": "paragraph", "text": "The earth produces." },
        { "type": "paragraph", "text": "The Hebrew actually makes that productivity conspicuous, using closely related language for the earth sprouting what sprouts from it. Other languages preserve the productive movement in different ways." },
        { "type": "paragraph", "text": "But we should not make the earth into another mind." },
        { "type": "paragraph", "text": "Genesis does not tell us that the earth thinks, chooses, plans, or develops an intention competing with God's." },
        { "type": "paragraph", "text": "Ancient Jewish readers remind us to be cautious here. Some noticed differences between God's command and the description of the result and developed striking interpretations in which the earth was treated almost as though it had responded imperfectly to God's instruction." },
        { "type": "paragraph", "text": "Whether or not we follow those interpretations, they expose a useful boundary." },
        { "type": "paragraph", "text": "The text really does give the earth a productive role." },
        { "type": "paragraph", "text": "It does not explicitly tell us that the earth possesses an independent intention." },
        { "type": "paragraph", "text": "So perhaps the smaller observation is the more interesting one:" },
        { "type": "paragraph", "text": "God remains the disclosed intentional center while something He has made now functions within what He intends to happen next." },
        { "type": "paragraph", "text": "God has not become less visible." },
        { "type": "paragraph", "text": "Creation has acquired a function." },
        { "type": "paragraph", "text": "The narrative seems comfortable holding both together." }
      ]
    },
    {
      "title": "The Future Inside the Fruit",
      "blocks": [
        { "type": "paragraph", "text": "And then we encounter seed." },
        { "type": "paragraph", "text": "This is easy to miss because seed is so ordinary to us." },
        { "type": "paragraph", "text": "But nothing quite like it has appeared in the story before." },
        { "type": "paragraph", "text": "A seed points beyond the thing that presently exists." },
        { "type": "paragraph", "text": "A fruit tree does not merely produce fruit. The fruit contains something through which another tree can grow." },
        { "type": "paragraph", "text": "An ancient Jewish reader, Nachmanides, noticed essentially this feature centuries ago. He understood the seed-bearing description as providing for the continuation of what had been produced." },
        { "type": "paragraph", "text": "We do not need to follow every conclusion he drew to recognize what he saw." },
        { "type": "paragraph", "text": "Seed makes continuation possible." },
        { "type": "paragraph", "text": "That means God's disclosed intention now reaches beyond the initially narrated plants." },
        { "type": "paragraph", "text": "Genesis has not told us that creation will last forever." },
        { "type": "paragraph", "text": "But for the first time, we have strong reason to think beyond the immediate specimen standing before us." },
        { "type": "paragraph", "text": "The language about things producing according to their kinds adds another dimension." },
        { "type": "paragraph", "text": "Continuation is not presented as indeterminate." },
        { "type": "paragraph", "text": "There is pattern." },
        { "type": "paragraph", "text": "What God creates contains capacities through which subsequent growth can occur without Genesis needing to narrate a new creative utterance every time another plant appears." },
        { "type": "paragraph", "text": "Perhaps there is wisdom in designing something capable of carrying a function forward rather than requiring a fresh narrated intervention for every new instance." },
        { "type": "paragraph", "text": "Genesis does not tell us that directly." },
        { "type": "paragraph", "text": "But seed has given us reason to ask." }
      ]
    },
    {
      "title": "And Now You Can Look",
      "blocks": [
        { "type": "paragraph", "text": "This is where the third day quietly changes the reader's situation." },
        { "type": "paragraph", "text": "Think about where Genesis began." },
        { "type": "paragraph", "text": "The beginning." },
        { "type": "paragraph", "text": "The deep." },
        { "type": "paragraph", "text": "The waters." },
        { "type": "paragraph", "text": "The Spirit—or wind—of God." },
        { "type": "paragraph", "text": "The first light." },
        { "type": "paragraph", "text": "The expanse." },
        { "type": "paragraph", "text": "These are not realities whose original appearance the reader can simply go outside and inspect." },
        { "type": "paragraph", "text": "But now:" },
        { "type": "paragraph", "text": "Earth." },
        { "type": "paragraph", "text": "Seas." },
        { "type": "paragraph", "text": "Plants." },
        { "type": "paragraph", "text": "Trees." },
        { "type": "paragraph", "text": "Fruit." },
        { "type": "paragraph", "text": "Seed." },
        { "type": "paragraph", "text": "You know these things." },
        { "type": "paragraph", "text": "You can stand on land." },
        { "type": "paragraph", "text": "You can look at the sea." },
        { "type": "paragraph", "text": "You can pick fruit from a tree." },
        { "type": "paragraph", "text": "You can hold a seed between two fingers." },
        { "type": "paragraph", "text": "Something has changed." },
        { "type": "paragraph", "text": "At the beginning of Genesis, we are overwhelmingly dependent upon what we are being told about realities we cannot independently inspect." },
        { "type": "paragraph", "text": "By the third day, the narrative increasingly points toward realities we inhabit." },
        { "type": "paragraph", "text": "That does not prove how creation happened." },
        { "type": "paragraph", "text": "Seeing a seed germinate does not allow us to reconstruct Genesis 1." },
        { "type": "paragraph", "text": "But it does change the reader's evidentiary situation." },
        { "type": "paragraph", "text": "The story says seed." },
        { "type": "paragraph", "text": "And you can look at seed." },
        { "type": "paragraph", "text": "The story describes vegetation bearing seed." },
        { "type": "paragraph", "text": "And you can encounter that regularity yourself." },
        { "type": "paragraph", "text": "The evidence has begun to leave the page." },
        { "type": "paragraph", "text": "Not evidence proving every interpretation of Genesis." },
        { "type": "paragraph", "text": "Something more modest." },
        { "type": "paragraph", "text": "The world described by the narrative increasingly contains regularities the reader can encounter outside the narrative." },
        { "type": "paragraph", "text": "Testimony has not disappeared." },
        { "type": "paragraph", "text": "The reader simply has another kind of correspondence available." }
      ]
    },
    {
      "title": "Words Still Matter",
      "blocks": [
        { "type": "paragraph", "text": "That does not mean words have become unnecessary." },
        { "type": "paragraph", "text": "Quite the opposite." },
        { "type": "paragraph", "text": "When we compared translations, we discovered how much language can change what becomes easy to notice." },
        { "type": "paragraph", "text": "Spanish made uncovering particularly vivid." },
        { "type": "paragraph", "text": "Korean made aspects of production and emergence more conspicuous." },
        { "type": "paragraph", "text": "Arabic foregrounded generativity." },
        { "type": "paragraph", "text": "Other translations simplified details about seed or kinds while preserving the larger movement." },
        { "type": "paragraph", "text": "And sometimes a freer translation made an interpretation explicit that the Hebrew itself left for the reader to infer." },
        { "type": "paragraph", "text": "That taught us something important." },
        { "type": "paragraph", "text": "Translations can change our resolution without necessarily changing the Person we encounter." },
        { "type": "paragraph", "text": "God still speaks." },
        { "type": "paragraph", "text": "Reality still corresponds." },
        { "type": "paragraph", "text": "God still names." },
        { "type": "paragraph", "text": "God still sees." },
        { "type": "paragraph", "text": "God still evaluates." },
        { "type": "paragraph", "text": "God still continues." },
        { "type": "paragraph", "text": "The vocabulary moves more than the Person does." },
        { "type": "paragraph", "text": "But some translations let us inspect particular questions at higher resolution than others." },
        { "type": "paragraph", "text": "That is why scholarship matters." },
        { "type": "paragraph", "text": "Hebrew helped us." },
        { "type": "paragraph", "text": "Greek helped us." },
        { "type": "paragraph", "text": "Spanish helped us." },
        { "type": "paragraph", "text": "Korean helped us." },
        { "type": "paragraph", "text": "Arabic and Swahili helped us." },
        { "type": "paragraph", "text": "Ancient Jewish readers noticed things we had missed." },
        { "type": "paragraph", "text": "Modern scholars challenged assumptions we were beginning to make." },
        { "type": "paragraph", "text": "But none of them owns the encounter." },
        { "type": "paragraph", "text": "You do not need to become a scholar before you are allowed to start paying attention." }
      ]
    },
    {
      "title": "We Still Don't Know What the Spirit Is",
      "blocks": [
        { "type": "paragraph", "text": "And here is perhaps the strangest thing." },
        { "type": "paragraph", "text": "Near the beginning, Genesis introduced the *ruach Elohim* over the waters." },
        { "type": "paragraph", "text": "Spirit of God?" },
        { "type": "paragraph", "text": "Wind from God?" },
        { "type": "paragraph", "text": "Breath?" },
        { "type": "paragraph", "text": "The language has generated questions for a very long time." },
        { "type": "paragraph", "text": "Genesis 1:9-13 does not stop to settle them for us." },
        { "type": "paragraph", "text": "Nor does the narrative tell us what subsequently happens to the *ruach Elohim*. It does not report a departure. Neither does that silence permit us simply to declare a continuing location or function." },
        { "type": "paragraph", "text": "The question remains open." },
        { "type": "paragraph", "text": "And yet we know more about God than we did before." },
        { "type": "paragraph", "text": "We have watched Him speak." },
        { "type": "paragraph", "text": "We have watched what He said correspond substantially with what happened." },
        { "type": "paragraph", "text": "We have watched Him distinguish." },
        { "type": "paragraph", "text": "Gather." },
        { "type": "paragraph", "text": "Name." },
        { "type": "paragraph", "text": "See." },
        { "type": "paragraph", "text": "Evaluate." },
        { "type": "paragraph", "text": "Continue." },
        { "type": "paragraph", "text": "We have watched created reality acquire productive and future-oriented capacities." },
        { "type": "paragraph", "text": "The unresolved question has not disappeared." },
        { "type": "paragraph", "text": "But neither has the evidence." },
        { "type": "paragraph", "text": "That distinction matters." },
        { "type": "paragraph", "text": "A question is not the same thing as doubt." },
        { "type": "paragraph", "text": "Uncertainty about one claim does not require uncertainty about every other claim." },
        { "type": "paragraph", "text": "\"I don't know\" can be an intellectually responsible answer to one question while \"I have substantial evidence for this\" remains an intellectually responsible answer to another." },
        { "type": "paragraph", "text": "The Person can remain mysterious without remaining a stranger." }
      ]
    },
    {
      "title": "Perhaps This Is What Revelation Feels Like",
      "blocks": [
        { "type": "paragraph", "text": "We should be careful here." },
        { "type": "paragraph", "text": "Genesis never stops and tells us:" },
        { "type": "quote", "text": "This is why I am revealing creation this way." },
        { "type": "paragraph", "text": "The chapter may be doing many things at once." },
        { "type": "paragraph", "text": "Readers have reasonably seen order, function, creation, purpose, sacred space, and other concerns in this chapter." },
        { "type": "paragraph", "text": "Our discovery does not need to displace them." },
        { "type": "paragraph", "text": "Instead, ask a smaller question:" },
        { "type": "paragraph", "text": "What has this narrative actually made possible for its reader?" },
        { "type": "paragraph", "text": "We have heard God's intention." },
        { "type": "paragraph", "text": "We have encountered resulting reality." },
        { "type": "paragraph", "text": "We have seen substantive correspondence repeat." },
        { "type": "paragraph", "text": "We have accumulated history with the Speaker." },
        { "type": "paragraph", "text": "We have been given names." },
        { "type": "paragraph", "text": "We have moved toward increasingly familiar realities." },
        { "type": "paragraph", "text": "And now some of those realities contain regularities we can observe ourselves." },
        { "type": "paragraph", "text": "Meanwhile, enormous questions remain unanswered." },
        { "type": "paragraph", "text": "That is an interesting way to get to know someone." },
        { "type": "paragraph", "text": "Not exhaustive explanation." },
        { "type": "paragraph", "text": "Not evidence-free demand." },
        { "type": "paragraph", "text": "Disclosure." },
        { "type": "paragraph", "text": "Observation." },
        { "type": "paragraph", "text": "Questions." },
        { "type": "paragraph", "text": "More disclosure." },
        { "type": "paragraph", "text": "More observation." },
        { "type": "paragraph", "text": "History." },
        { "type": "paragraph", "text": "And the choice to keep watching." },
        { "type": "paragraph", "text": "We cannot yet prove that cultivating trust is the primary reason Genesis has been arranged this way." },
        { "type": "paragraph", "text": "But the arrangement gives the reader something from which trust can reasonably grow." },
        { "type": "paragraph", "text": "That is already significant." }
      ]
    },
    {
      "title": "You Were Never Required to Know Everything First",
      "blocks": [
        { "type": "paragraph", "text": "Perhaps that is one of the most encouraging things about this story." },
        { "type": "paragraph", "text": "Genesis does not require you to solve *ruach Elohim* before you can notice that God's disclosed intentions repeatedly correspond with what follows." },
        { "type": "paragraph", "text": "It does not require you to reconstruct ancient cosmology before you can notice that God names." },
        { "type": "paragraph", "text": "It does not require you to understand reproductive biology before you can recognize what seed makes possible." },
        { "type": "paragraph", "text": "And it does not require you to stop asking questions before you are allowed to become more confident about something the evidence has repeatedly supported." },
        { "type": "paragraph", "text": "You can know something without knowing everything." },
        { "type": "paragraph", "text": "You can ask a question without converting the question into doubt." },
        { "type": "paragraph", "text": "You can become more confident about one thing while remaining uncertain about another." },
        { "type": "paragraph", "text": "You can keep learning." },
        { "type": "paragraph", "text": "That posture does not belong uniquely to scholars." },
        { "type": "paragraph", "text": "It belongs to humans." }
      ]
    },
    {
      "title": "Hold the Seed Again",
      "blocks": [
        { "type": "paragraph", "text": "So return to the seed." },
        { "type": "paragraph", "text": "Hold it." },
        { "type": "paragraph", "text": "You still do not know everything happening inside it." },
        { "type": "paragraph", "text": "You could spend a lifetime studying biology and still find more questions." },
        { "type": "paragraph", "text": "But your unanswered questions do not require you to pretend you know nothing about seeds." },
        { "type": "paragraph", "text": "Plant one." },
        { "type": "paragraph", "text": "Watch." },
        { "type": "paragraph", "text": "Genesis began by telling us about a world we could not see." },
        { "type": "paragraph", "text": "By the third day, that world is becoming increasingly recognizable as ours." },
        { "type": "paragraph", "text": "And the Person at the center of the story has not become less mysterious." },
        { "type": "paragraph", "text": "But He has become less unfamiliar." },
        { "type": "paragraph", "text": "We have heard Him." },
        { "type": "paragraph", "text": "We have watched Him." },
        { "type": "paragraph", "text": "We have begun to acquire history with Him." },
        { "type": "paragraph", "text": "And now, increasingly, we can look around." },
        { "type": "paragraph", "text": "The mystery remains." },
        { "type": "paragraph", "text": "So does the invitation." },
        { "type": "paragraph", "text": "**Keep watching.**" }
      ]
    }
  ]
};
