import type { EssayEntry } from './types';
import { assetUrl } from '@/lib/assets';

export const genesisLanguageEssay: EssayEntry = {
  "title": "Does God Change When the Language Does?",
  "slug": "does-god-change-when-the-language-does",
  "deck": "Reading Genesis across translation, salience, and shared attention.",
  "category": "religion",
  "status": "draft",
  "publicationDate": "September 2026",
  "readingTime": "13 minute read",
  "image": assetUrl('/images/whydive/does-god-change-when-the-language-does-hero.png'),
  "sourceNote": "This essay is adapted from an internal Relational Knowledge of God reflection on Genesis, translation, reader salience, and the discipline of testing discoveries across language and community.",
  "sections": [
    {
      "paragraphs": [
        "I was reading Genesis in English when an uncomfortable question occurred to me.",
        "What if I were reading it in Spanish?",
        "Not because Spanish is somehow special. It was simply the first other language that came to mind.",
        "Would I be meeting the same God?",
        "The question grew.",
        "What if I were reading Genesis in Korean? Swahili? Arabic?",
        "What about someone reading it in Greek two thousand years ago?",
        "We say these people are reading the same Bible. But they are obviously not reading the same words.",
        "So how much of the God I thought I was discovering in Genesis was actually **God**—and how much was English?",
        "That seemed worth finding out."
      ]
    },
    {
      "title": "Watching Before Explaining",
      "paragraphs": [
        "I had begun reading Genesis with a fairly simple discipline.",
        "I wanted to temporarily set aside as much as I could of what I had already been told about God and pay attention to what the text actually showed me.",
        "Not because everything I had previously learned was wrong.",
        "And certainly not because I imagined I could become a reader without assumptions.",
        "I simply wanted to watch.",
        "Genesis says God creates.",
        "Then God remains involved with what He has created.",
        "God speaks.",
        "Something happens corresponding to what He expressed.",
        "God looks.",
        "God regards the light positively.",
        "God distinguishes light from darkness.",
        "God names them Day and Night.",
        "And then He continues working.",
        "None of that required me to construct a systematic theology.",
        "I was watching a Person act.",
        "That distinction became increasingly important.",
        "I wasn't beginning with a list of God's attributes and looking for verses that supported them.",
        "I was asking:",
        "**What kind of Person am I actually watching?**",
        "And then came the language question."
      ]
    },
    {
      "title": "What Happens When the Words Move?",
      "paragraphs": [
        "So we began comparing.",
        "Hebrew.",
        "Ancient Greek.",
        "Latin.",
        "English.",
        "Spanish.",
        "Korean.",
        "Swahili.",
        "Arabic.",
        "I expected differences.",
        "I wasn't prepared for how interesting some of them would be.",
        "Consider the condition of the earth in Genesis 1:2.",
        "Many English readers meet an earth that is **“formless and void”** or **“formless and empty.”**",
        "A Spanish reader may encounter *desordenada y vacía*—**disordered and empty**.",
        "Then we looked at the ancient Greek Septuagint.",
        "Its description moves in another direction again, using words that can convey something like **unseen and unformed**.",
        "Those aren't identical pictures.",
        "“Formless.”",
        "“Empty.”",
        "“Disordered.”",
        "“Unseen.”",
        "“Unformed.”",
        "Immediately I had to become more careful.",
        "If I build a substantial conclusion about God's character upon one of those English adjectives, another reader may not even have been given that adjective.",
        "The same thing happened with another expression in that verse.",
        "Many English Bibles say:",
        "**“the Spirit of God”**",
        "was moving or hovering over the waters.",
        "But the Hebrew expression *ruach Elohim* raises a familiar interpretive question because *ruach* can refer to **spirit**, **wind**, or **breath**.",
        "Some readers can therefore encounter something closer to **a wind from God**.",
        "That is not an insignificant difference.",
        "If I build an elaborate conclusion upon the identity of the *ruach* while pretending the translation question doesn't exist, I may be asking the text to support more than it presently can.",
        "The investigation was already doing something useful.",
        "It wasn't making Genesis meaningless.",
        "It was teaching me where to become less certain.",
        "And then we found something that changed one of my observations even more directly."
      ]
    },
    {
      "title": "When an Absence Isn't Equally Absent",
      "paragraphs": [
        "I had noticed something about the creation sequence.",
        "After God creates light, He sees that the light is good.",
        "That appraisal interested me.",
        "Then creation continues.",
        "Later, as I moved toward the second day, another feature became noticeable: in the Hebrew textual tradition underlying most of our English Bibles, Day Two lacks the familiar statement that God saw that it was good.",
        "That silence looked interesting.",
        "Why wasn't Day Two called good?",
        "Was there something about unfinished work?",
        "Was the absence telling us something about God?",
        "Those are reasonable questions.",
        "But then we looked at the ancient Greek Septuagint.",
        "There, the second day can include the positive appraisal.",
        "Suddenly the silence I had been examining wasn't equally silent across the ancient textual traditions.",
        "That doesn't mean the question was foolish.",
        "It means its status changed.",
        "I could still notice the absence in the Hebrew tradition.",
        "I could investigate it.",
        "But I could no longer casually build a major conclusion about God's character upon that absence without acknowledging the textual complication.",
        "I didn't have to throw away everything I had learned because one observation weakened.",
        "I simply had to stop claiming more than that observation could bear.",
        "That experience strengthened one of the disciplines we had already begun developing:",
        "**Notice the silence, but follow the speech.**",
        "And eventually it produced another:",
        "**Never protect a discovery from another language.**"
      ]
    },
    {
      "title": "Sometimes Another Language Shows You Something",
      "paragraphs": [
        "Not every difference weakened an observation.",
        "Some differences helped us see.",
        "Genesis 1:3 is usually familiar to English readers as:",
        "**“Let there be light.”**",
        "I had been describing this as God expressing **intention**.",
        "That choice mattered to me.",
        "Calling the statement merely a “command” can quietly encourage us to imagine an interaction the narrative itself does not describe:",
        "God commands.",
        "Something receives the command.",
        "Something obeys.",
        "But Genesis doesn't narrate light considering an instruction and complying with it.",
        "God speaks concerning a reality that is to exist, and the reality comes to be.",
        "Korean hadn't proved our interpretation. A translation cannot become evidence for a meaning simply because it expresses that meaning more clearly than another translation does.",
        "But Korean had done something valuable: **it had drawn our attention to a possibility.**",
        "Was “Let there be light” best understood only as a command? Or did the Hebrew itself allow us to see God expressing His will or intention concerning what was to exist?",
        "So we returned to the Hebrew—not to find words that would defend what we now wanted to believe, but to ask whether the distinction Korean had made noticeable was actually present there.",
        "The Hebrew form translated “Let there be” is a **jussive**, a grammatical form used to express volition. Depending on context, such a form can function as a command, but its territory is broader than command alone: it concerns what the speaker wills, desires, or directs to be.",
        "That mattered.",
        "It did not mean that “command” was suddenly wrong. Nor did it mean that Korean had discovered a secret meaning unavailable to everyone else.",
        "It meant that our earlier description—**God expresses intention concerning a reality that is to exist**—remained compatible with the Hebrew evidence after we tested it.",
        "That was what had survived.",
        "And the experience taught us something larger.",
        "Another language had not given us a new doctrine. It had caused us to notice a feature worth investigating. We brought that observation back to the textual evidence, and the evidence gave us reason to keep it.",
        "That distinction became important:",
        "**Another language should not become evidence simply because it says something clearly. But it can help us notice something worth testing.**",
        "Sometimes translation preserves.",
        "Sometimes it obscures.",
        "Sometimes it interprets.",
        "And sometimes it **illuminates**—not by creating meaning, but by making something easier to notice.",
        "That realization would eventually change how I thought about other readers too.",
        "But first, something larger was becoming visible."
      ]
    },
    {
      "title": "The Vocabulary Moved More Than the Person Did",
      "paragraphs": [
        "I stepped back from the individual words.",
        "Look at how much had moved.",
        "The earth could be described as:",
        "**formless**",
        "**empty**",
        "**disordered**",
        "**unseen**",
        "**unformed**",
        "The *ruach Elohim* could confront a reader as:",
        "**the Spirit of God**",
        "or language moving toward:",
        "**a wind from God**",
        "A temporal expression could appear as:",
        "**one day**",
        "or become:",
        "**the first day**",
        "Even the presence of a positive appraisal could differ at one point between ancient textual traditions.",
        "Those differences matter.",
        "But now step farther back.",
        "Who creates?",
        "**God.**",
        "Who remains involved with the world that has been introduced?",
        "**God.**",
        "Who speaks?",
        "**God.**",
        "Whose expressed intention is followed by corresponding reality?",
        "**God's.**",
        "Who attends to what has happened?",
        "**God.**",
        "Who positively appraises?",
        "**God.**",
        "Who distinguishes?",
        "**God.**",
        "Who names?",
        "**God.**",
        "Who continues working?",
        "**God.**",
        "That's when the surprising possibility became visible.",
        "**The vocabulary moved more than the Person did.**",
        "Not because every detail survived unchanged.",
        "It didn't.",
        "Not because translation is transparent.",
        "It isn't.",
        "But perhaps some of the most elemental things Genesis reveals about God are carried not only by individual words but by **patterns of behavior**.",
        "We are watching someone do things.",
        "And behavior can sometimes survive translation remarkably well."
      ]
    },
    {
      "title": "A Microscope and a Wide-Angle Lens",
      "paragraphs": [
        "That realization changed the way I wanted to read.",
        "I now imagine two lenses.",
        "The first is a **microscope**.",
        "Take the word *tov*.",
        "Most English readers encounter:",
        "**good.**",
        "So:",
        "“God saw that the light was good.”",
        "But what precisely is being communicated by *tov*?",
        "How much of our English concept of “good” should we bring into it?",
        "Is the appraisal moral?",
        "Functional?",
        "Aesthetic?",
        "Pleasant?",
        "Appropriate?",
        "Some combination our English word doesn't neatly capture?",
        "The microscope makes me cautious.",
        "I should not make the English word **good** carry every theological meaning I associate with goodness and then place all of that back into Genesis 1:4.",
        "But now switch lenses.",
        "Use the **wide-angle lens**.",
        "Whatever precision *tov* ultimately requires, something much less fragile is happening.",
        "**God brings something about.**",
        "**God attends to it.**",
        "**God evaluates it positively.**",
        "**God then continues creating.**",
        "My uncertainty about the exact semantic range of *tov* does not erase the narrated act of divine appraisal.",
        "In fact, after examining the detail, I may become **less confident about exactly what the appraisal means while becoming more confident that attending and appraising are part of the Person I am watching.**",
        "That was important.",
        "The microscope doesn't exist merely to make us uncertain.",
        "And the wide-angle lens doesn't exist to rescue conclusions we prefer.",
        "They constrain each other.",
        "The microscope can tell the wide-angle lens:",
        "**The details won't support that pattern.**",
        "The wide-angle lens can tell the microscope:",
        "**Don't make one difficult word carry the whole portrait.**",
        "Sometimes uncertainty at the microscope level does not destroy confidence at the wide-angle level.",
        "It simply tells us **what kind of confidence we are entitled to have**."
      ]
    },
    {
      "title": "Then Another Problem Appeared",
      "paragraphs": [
        "Language wasn't the only variable.",
        "I was.",
        "So are you.",
        "Culture affects what becomes noticeable to us.",
        "So does prior theology.",
        "Education.",
        "Profession.",
        "Personality.",
        "Life experience.",
        "Even pain.",
        "Two people can read the same paragraph and have their attention caught by different things.",
        "For a long time, I would have regarded that mainly as a problem called **bias**.",
        "It certainly can be.",
        "But I am no longer convinced that is the whole story.",
        "Consider a simple statement:",
        "**God separated the light from the darkness.**",
        "One reader might immediately notice:",
        "**God establishes distinctions.**",
        "Another might notice:",
        "**God does not destroy the darkness.**",
        "Someone else might notice:",
        "**God distinguishes before He names.**",
        "Another might be struck by the fact that both realities remain after the separation.",
        "Are all of those observations equally justified?",
        "I don't know merely because someone noticed them.",
        "But neither should I dismiss an observation simply because it wasn't the one that occurred to me.",
        "Perhaps your experience makes you sensitive to something I routinely overlook.",
        "Perhaps your culture has trained you to notice relationships that mine pushes into the background.",
        "Perhaps an engineer notices structure.",
        "A counselor notices attention.",
        "Someone who has lived under oppressive power notices how authority is exercised.",
        "Someone whose culture places enormous importance on community notices relationships an individualistic reader barely sees.",
        "None of those experiences makes an interpretation true.",
        "But they can affect **salience**—what becomes visible enough for us to investigate.",
        "That gave us another principle:",
        "**Salience generates questions and candidate discoveries. Evidence adjudicates them.**",
        "Your experience cannot make the text say something it doesn't.",
        "But your experience might help you ask a question I never thought to ask."
      ]
    },
    {
      "title": "“Show Me Where You Saw That”",
      "paragraphs": [
        "That may be one of the most important things I learned from this experiment.",
        "Another reader is not merely someone whose interpretation I need to test against mine.",
        "They may be able to contribute something.",
        "So imagine several people reading Genesis together.",
        "Different ages.",
        "Different professions.",
        "Perhaps different cultures.",
        "Ideally, even different languages.",
        "Someone says:",
        "“What catches my attention is that God doesn't destroy the darkness.”",
        "I didn't notice that.",
        "What should I do?",
        "I don't have to accept it because their experience is different from mine.",
        "I don't have to reject it because mine is different from theirs.",
        "I can ask:",
        "**“Show me where you saw that.”**",
        "Then we look again.",
        "Perhaps it is there.",
        "Perhaps it isn't.",
        "Perhaps the observation is stronger than either of us initially realized.",
        "Perhaps another translation complicates it.",
        "Perhaps Hebrew weakens it.",
        "Perhaps the larger literary movement strengthens it.",
        "Perhaps the next verse destroys it completely.",
        "Good.",
        "We are trying to know the Person, not protect our discoveries about Him."
      ]
    },
    {
      "title": "Not Everything We Discover Has the Same Weight",
      "paragraphs": [
        "This also means we need more vocabulary than **true** and **false**.",
        "Our own investigation produced different kinds of discoveries.",
        "Some became **high-confidence findings**.",
        "God creates.",
        "God remains involved.",
        "God speaks.",
        "God attends.",
        "God appraises.",
        "God differentiates.",
        "God names.",
        "God continues.",
        "Other observations became **strong inferences**.",
        "For example, goodness appears in the narrative before there is any human moral obligation to fulfill. Whatever else *tov* will eventually mean, the first “good” we encounter is God's appraisal of what He has made.",
        "Some discoveries became **translation-sensitive**.",
        "What precisely is *ruach Elohim*?",
        "How exactly should *tohu wabohu* be represented?",
        "What should we make of the missing second-day appraisal when an ancient Greek textual tradition contains one?",
        "Some remained **provisional hypotheses**.",
        "Is Genesis doing more than showing us what God makes?",
        "Might it gradually be teaching us how God **sees** what He makes?",
        "Is the reader being permitted, little by little, to look at reality from God's point of view?",
        "I find that possibility fascinating.",
        "But fascinating isn't the same thing as established.",
        "So we keep watching.",
        "Other things simply remain **open questions**.",
        "And some things we initially thought were stronger had to be weakened.",
        "That is not a defect in the process.",
        "It is part of knowing what we actually know.",
        "A hypothesis should sound like a hypothesis.",
        "An open question should remain open.",
        "An anomaly should not be hidden because it makes our argument untidy.",
        "And something that repeatedly survives serious attempts to challenge it should not be treated as though we know nothing simply because absolute certainty is unavailable.",
        "Perhaps a useful rule is:",
        "**Confidence should grow in proportion to what a discovery survives.**",
        "That gives us something better than both dogmatism and endless uncertainty.",
        "It gives us **confidence without closure**."
      ]
    },
    {
      "title": "The Reader Doesn't Need to Become a Hebrew Scholar",
      "paragraphs": [
        "This experiment also brought me back, somewhat unexpectedly, to where I began.",
        "I am not a Hebrew scholar.",
        "I am not a professional biblical scholar.",
        "I started by reading the Bible available to me and paying attention.",
        "After that, the questions took us into Hebrew, Greek, ancient translations, translation theory, textual differences, narratology, culture, and the psychology of perception.",
        "Those things mattered.",
        "Some corrected me.",
        "Some strengthened what I had noticed.",
        "Some generated completely new questions.",
        "But after all that examination, I did not discover that the original reader was foolish to begin by simply watching God in English.",
        "In fact, some of the most elemental things I noticed were among the things that survived most strongly.",
        "That suggests a distinction I find increasingly important.",
        "You may need scholarship to test some of what you think you see.",
        "You do not need to become a scholar **before you are allowed to start looking**."
      ]
    },
    {
      "title": "What If We Tried This Together?",
      "paragraphs": [
        "So I wonder what would happen if groups of people tried this deliberately.",
        "Take a small section of Scripture.",
        "Don't begin with a commentary.",
        "Don't begin by debating doctrine.",
        "Don't begin by asking everyone to forget everything they know. We probably cannot do that anyway.",
        "Just become aware that you bring something with you.",
        "Then look.",
        "Use the microscope.",
        "What exactly happens?",
        "Who acts?",
        "What is said?",
        "What isn't said?",
        "What follows?",
        "Then use the wide-angle lens.",
        "What have you repeatedly watched God do?",
        "What kind of Person seems to be emerging?",
        "Then compare what you noticed.",
        "If someone sees something you didn't:",
        "**“Show me where you saw that.”**",
        "If possible, include someone whose background differs from yours.",
        "Someone younger.",
        "Someone older.",
        "Someone from another culture.",
        "Someone with another profession.",
        "Someone reading the passage in another language.",
        "And see what happens.",
        "Not because everybody's interpretation must be correct.",
        "Not because truth changes with culture.",
        "But because none of us should assume that what **I noticed** exhausts what **there is to notice**."
      ]
    },
    {
      "title": "Comprehensive, Not Exhaustive",
      "paragraphs": [
        "That may be the posture I am looking for.",
        "Not an exhaustive reading.",
        "A comprehensive one.",
        "Look closely.",
        "Look widely.",
        "Listen to other readers.",
        "Test what you notice.",
        "Investigate difficulties.",
        "Keep the anomalies.",
        "Name your uncertainty.",
        "Carry forward what survives.",
        "And keep watching.",
        "There are things about God's character that I now hold with considerably greater confidence than when I began.",
        "Not because a denomination told me to.",
        "Not because one scholar said so.",
        "And not merely because I saw them once.",
        "They have survived examination.",
        "But I don't want that confidence to become a wall around the Person I am trying to know.",
        "The next passage still gets to correct me.",
        "Another language gets to challenge me.",
        "Another reader gets to show me something I missed.",
        "That is not a threat to knowing God.",
        "Perhaps it is part of how finite people learn to know someone none of us can exhaust.",
        "So I am left with an invitation rather than a conclusion.",
        "Find some people.",
        "Open the text.",
        "Look carefully.",
        "And when someone says,",
        "“I see something,”",
        "instead of immediately deciding whether they are right or wrong, try asking:",
        "**“Show me.”**",
        "Then look again.",
        "Maybe together we will see a little more."
      ]
    }
  ]
};
