import type { WhitepaperEntry } from './types';

export const whitepaperEntries: WhitepaperEntry[] = [
  {
    title: 'WhyDive',
    subtitle: 'Strengthening Judgment Under Evidence Constraints',
    slug: 'strengthening-judgment-under-evidence-constraints',
    layer: 1,
    layerTitle: 'Foundational Framework',
    question: 'Why does WhyDive exist?',
    audience: ['General public', 'Investors', 'Researchers', 'Partners', 'Thought leaders'],
    status: 'planned',
    purpose: [
      'Define the human problem',
      'Define judgment, reasoning, decision-making, evidence, action, and human flourishing',
      'Establish the philosophical foundation for the framework',
    ],
    sourceDocuments: [
      'WhyDive Foundational Thesis v1',
      'Strong Conclusions Require Strong Evidence',
      'WhyDive, Chart-Ed, and the Larger Mission',
    ],
  },
  {
    title: 'WhyDive',
    subtitle: 'Bounded Reasoning Development System',
    slug: 'bounded-reasoning-development-system',
    layer: 2,
    layerTitle: 'Framework Architecture',
    question: 'How does WhyDive operate?',
    audience: ['Researchers', 'Technical reviewers', 'Investors performing diligence', 'System designers'],
    status: 'draft',
    purpose: [
      'Define the reasoning chain',
      'Explain how people recognize evidence boundaries, repair overreach, and make disciplined reasoning habitual',
      'Explain the architecture beneath application domains',
    ],
  },
  {
    title: 'WhyDive Education',
    subtitle: 'District Assessment and Development System',
    slug: 'whydive-education',
    layer: 3,
    layerTitle: 'Educational Implementation',
    question: 'How is WhyDive applied in education?',
    audience: ['District leaders', 'Curriculum directors', 'Superintendents'],
    status: 'planned',
    purpose: [
      'Define the district problem',
      'Explain adaptive assessment, developmental placement, growth pathways, and reporting',
      'Describe what evidence would validate the system',
    ],
    relationship: 'Application of WhyDive, not the parent framework.',
  },
  {
    title: 'WhyDive Reading',
    subtitle: 'Judgment Through Text',
    slug: 'whydive-reading',
    layer: 3,
    layerTitle: 'Educational Implementation',
    question: 'How does WhyDive diagnose textual reasoning?',
    audience: ['District leaders', 'Curriculum directors', 'Reading leaders'],
    status: 'planned',
    purpose: ['Explain textual evidence, interpretation, inference, and judgment formation through reading'],
    relationship: 'Domain expression within WhyDive Education.',
  },
  {
    title: 'WhyDive Charts',
    subtitle: 'Judgment Through Quantitative Evidence',
    slug: 'whydive-charts',
    layer: 3,
    layerTitle: 'Educational Implementation',
    question: 'How does WhyDive diagnose quantitative and chart-based reasoning?',
    audience: ['District leaders', 'Curriculum directors', 'Data literacy leaders'],
    status: 'planned',
    purpose: ['Explain charts, graphs, quantitative claims, evidence boundaries, and data-based judgment'],
    relationship: 'Domain expression within WhyDive Education.',
  },
  {
    title: 'Data Literacy Standards',
    subtitle: 'Global Framework for Data Literacy Development',
    slug: 'data-literacy-standards',
    layer: 4,
    layerTitle: 'Data Literacy Pathway',
    question: 'How does WhyDive appear through data literacy?',
    audience: ['Researchers', 'Curriculum developers', 'Global partners', 'Standards bodies'],
    status: 'planned',
    purpose: ['Define DLL 1-16, strands, developmental bands, ethos arc, and telos arc'],
    relationship: 'First full domain expression of WhyDive.',
  },
  {
    title: 'Chart-Ed Framework',
    subtitle: 'Operationalizing Data Literacy',
    slug: 'chart-ed-framework',
    layer: 4,
    layerTitle: 'Data Literacy Pathway',
    question: 'How does the DLS become usable for educators?',
    audience: ['Educators', 'Curriculum developers', 'Product reviewers'],
    status: 'planned',
    purpose: ['Explain assessment, reporting, instructional supports, and practical use'],
    relationship: 'Built from DLS.',
  },
  {
    title: 'WhyDive Business',
    subtitle: 'Evidence to Decisions in Organizations',
    slug: 'whydive-business',
    layer: 5,
    layerTitle: 'Future Domain Implementations',
    question: 'How do organizations move from evidence to decisions responsibly?',
    audience: ['Business leaders', 'Operators', 'Organizational decision-makers'],
    status: 'planned',
    purpose: ['Extend WhyDive into organizational judgment and decision-making'],
  },
  {
    title: 'WhyDive Policy',
    subtitle: 'Public Judgment Under Uncertainty',
    slug: 'whydive-policy',
    layer: 5,
    layerTitle: 'Future Domain Implementations',
    question: 'How should public decisions be formed under uncertainty?',
    audience: ['Policy leaders', 'Civic institutions', 'Researchers'],
    status: 'planned',
    purpose: ['Extend WhyDive into public evidence, uncertainty, and policy judgment'],
  },
  {
    title: 'WhyDive AI Evaluation',
    subtitle: 'Evaluating Synthetic Claims',
    slug: 'whydive-ai-evaluation',
    layer: 5,
    layerTitle: 'Future Domain Implementations',
    question: 'How should humans evaluate AI-generated claims?',
    audience: ['AI users', 'Organizations', 'Researchers', 'Educators'],
    status: 'planned',
    purpose: ['Extend WhyDive into AI-generated claims and synthetic information environments'],
  },
  {
    title: 'WhyDive Arguments',
    subtitle: 'Evidence and Claims in Public Discourse',
    slug: 'whydive-arguments',
    layer: 5,
    layerTitle: 'Future Domain Implementations',
    question: 'How should claims be evaluated in public discourse?',
    audience: ['Civic leaders', 'Educators', 'Public communicators'],
    status: 'planned',
    purpose: ['Extend WhyDive into argument evaluation and public reasoning'],
  },
  {
    title: 'WhyDive Higher Education',
    subtitle: 'Judgment Development Beyond K-12',
    slug: 'whydive-higher-education',
    layer: 5,
    layerTitle: 'Future Domain Implementations',
    question: 'How should judgment development continue beyond K-12?',
    audience: ['Higher education leaders', 'Faculty', 'Researchers'],
    status: 'planned',
    purpose: ['Extend WhyDive into post-secondary learning and professional formation'],
  },
];

export const whitepaperLayers = [1, 2, 3, 4, 5].map((layer) => {
  const papers = whitepaperEntries.filter((paper) => paper.layer === layer);
  return {
    layer,
    title: papers[0]?.layerTitle ?? `Layer ${layer}`,
    question: papers[0]?.question ?? '',
    papers,
  };
});
